build:
  nodes:
    coverage:
      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clover=coverage
            coverage:
              file: coverage

              # These formats are supported:
              # clover, cobertura, jacoco, python-cc, ruby-cc, go-cc, lcov
              format: php-clover